import "./globals.css";
import Provider from "./components/provider/Provider";

export const metadata = {
  title: "shop.co",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
